/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectionRouteRouteImport } from './routes/(protection)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicResourcesRouteRouteImport } from './routes/(public)/resources/route'
import { Route as publicResourcesIndexRouteImport } from './routes/(public)/resources/index'

const protectionRouteRoute = protectionRouteRouteImport.update({
  id: '/(protection)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicResourcesRouteRoute = publicResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicResourcesIndexRoute = publicResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicResourcesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/resources': typeof publicResourcesRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/resources/': typeof publicResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/resources': typeof publicResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protection)': typeof protectionRouteRoute
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/resources': typeof publicResourcesRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(public)/resources/': typeof publicResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/resources' | '/' | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resources'
  id:
    | '__root__'
    | '/(protection)'
    | '/(public)'
    | '/(public)/resources'
    | '/(public)/'
    | '/(public)/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectionRouteRoute: typeof protectionRouteRoute
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protection)': {
      id: '/(protection)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/resources': {
      id: '/(public)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof publicResourcesRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/resources/': {
      id: '/(public)/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof publicResourcesIndexRouteImport
      parentRoute: typeof publicResourcesRouteRoute
    }
  }
}

interface publicResourcesRouteRouteChildren {
  publicResourcesIndexRoute: typeof publicResourcesIndexRoute
}

const publicResourcesRouteRouteChildren: publicResourcesRouteRouteChildren = {
  publicResourcesIndexRoute: publicResourcesIndexRoute,
}

const publicResourcesRouteRouteWithChildren =
  publicResourcesRouteRoute._addFileChildren(publicResourcesRouteRouteChildren)

interface publicRouteRouteChildren {
  publicResourcesRouteRoute: typeof publicResourcesRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicResourcesRouteRoute: publicResourcesRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectionRouteRoute: protectionRouteRoute,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
