import type { QueryClient } from "@tanstack/react-query"
import type { PropsWithChildren } from "react"

export type RouterAppContext = {
    queryClient: QueryClient
}

export type QueryproviderProps = PropsWithChildren<{
    query: QueryClient
}>

export type RequestContext = {
    env: Env
    waitUntil: (promise: Promise<unknown>) => void
    passThroughOnException: () => void
}

// worker-configuration.d.ts is generated by `wrangler types` from
// wrangler.jsonc bindings + a live .dev.vars file; these two are Worker
// secrets (never committed), so they only exist here, not there. Set them
// with `wrangler secret put` (or in .dev.vars for local dev) per spec
// 0002's "Configuration required". Both the bare global `Env` (used by
// RequestContext above) and `Cloudflare.Env` (what `cloudflare:workers`'s
// own `env` export is actually typed as) need the augmentation.
interface WorkerSecrets {
    // wrangler.jsonc has no `vars` block, so `wrangler types` only ever
    // types whatever happens to be in .dev.vars at generation time; that
    // makes NODE_ENV unreliable there (it lives in .env.local, not
    // .dev.vars) even though it's a standard var, not a secret. Declared
    // here for the same reason as the others below.
    NODE_ENV: string
    TURNSTILE_SITE_KEY: string
    TURNSTILE_SECRET_KEY: string
    BETTER_AUTH_SECRET: string
    // not in spec 0001's own "Configuration required" list, but required
    // in practice, see lib/auth.ts's baseURL comment
    BETTER_AUTH_URL: string
    INFRA_OIDC_ISSUER_URL: string
    INFRA_OAUTH_CLIENT_ID: string
    // unset in dev, where Transspace is registered as a public,
    // no-secret Infra client (spec 0001 Configuration required)
    INFRA_OAUTH_CLIENT_SECRET?: string
    COOKIE_DOMAIN?: string
}

declare global {
    interface Env extends WorkerSecrets {}
    namespace Cloudflare {
        interface Env extends WorkerSecrets {}
    }
}